services:
  postgres:
    image: postgres:16
    container_name: recrut_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: recrut_user
      POSTGRES_PASSWORD: UnMotDePasseTrèsSimple
      POSTGRES_DB: recrut_db
    ports:
      - "5432:5432"
    volumes:
      - recrut_pgdata:/var/lib/postgresql/data

volumes:
  recrut_pgdata:
